# docker-compose.yml 用來定義 container 的環境。包含建構 container 的 images 還有 images 如何交互
version: "3.9"

services: 
    nginx:
        container_name: nginx
        image: nginx:1.19-alpine
        # 本機及容器掛載
        volumes:
            - ./nginx:/etc/nginx/conf.d/
            - ./LaravelProject/:/var/www/html/
        ports:
            - "80:80"
        depends_on: 
            - php
        restart: unless-stopped

    php:
        container_name: php
        # image: php:7.4-fpm
        build: 
            context: ./
            dockerfile: Dockerfile
        expose: 
            - "9000"
        volumes: 
            - ./LaravelProject/:/var/www/html/
        depends_on: 
            - db
            - redis

    db:
        container_name: db
        # image: mysql:5.7
        # restart: always
        # # ports: 
        # #     - "2222:2222"
        # # 測試不需要 volume 資料庫
        # # volumes:
        # #     - ./db_data:/var/lib/mysql
        # environment:
        #     MYSQL_ROOT_PASSWORD: practice123
        image: postgres
        restart: always
        ports: 
            - "5432:5432"
        environment:
            POSTGRES_PASSWORD: example
            POSTGRES_USER: user
            POSTGRES_DB: name
        volumes: 
            - ./env_config/postgres.conf:/etc/postgresql.conf
        command: postgres -c config_file=/etc/postgresql.conf

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080


    redis:
        container_name: redis
        image: redis:6.0
        expose:
            - "6379"
        # 除非真的要用，否則沒人在 volume redis
        # volumes: 
        #     - myredis:/usr/local/etc/redis/redis.conf
